version: '3.8'

services:
  # O Banco de dados de Cache
  redis:
    image: redis:alpine
    container_name: meu_redis_cache
    ports:
      - "6379:6379"

  # O seu microserviço FastAPI
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis